# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160513_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('online', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.EventType'),
        ),
    ]
