# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Numero')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='guide/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
        ),
    ]
