# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
