# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
